#!/usr/bin/env python

''' Christian 6/20
float_smoother.py: receives commands and controlls robot

SUBSCRIBES:
- `robot_twist`, receives commands of type `Twist`
- `robot_commands`, receives commands of type i32[5]

PUBLISHES:
- `/mobile_base/commands/velocity`: movement commands of type Twist (after smoothing)
- `/mobile_base/commands/sound`: sound commands of type Sound
- `/mobile_base/commands/{led1, led2}`: LED commands of type Led
=====================================================================================

- flashes LED #1, makes sound when robot moves backwards
- publishes `Twist` command every 10 ms
- supports e-brake (pressing `B` button makes robot stop immediately)
- has three types of smoothing mode, displayed by LED #2:
	- eco mode: accelerates and decelerates less quickly
	- sport mode: accelerates and decelerates more quickly
	- off mode: no smoothing
'''

import math
import rospy
from std_msgs.msg import Float32, Int32MultiArray
from geometry_msgs.msg import Twist
from kobuki_msgs.msg import Led, Sound

# SUBSCRIBERS
rospy.init_node('smoother', anonymous=True)
rospy.Subscriber('robot_twist', Twist, twist_callback) # TODO make twist_callback
rospy.Subscriber('robot_commands', Int32MultiArray, command_callback) # TODO make command_callback

# PUBLISHERS
velocity_pub = rospy.Publisher("/mobile_base/commands/velocity", Twist, queue_size=10)
sound_pub = rospy.Publisher("/mobile_base/commands/sound", Sound, queue_size=1)
led1_pub = rospy.Publisher("/mobile_base/commands/led1", Led, queue_size=1)
led2_pub = rospy.Publisher("/mobile_base/commands/led2", Led, queue_size=1)

# STATE
config_command = Int32MultiArray()
config_command.data = [0, 0, 0, 0, 0]
velocity_command = Twist() 

# CONFIG
DURATION_S = 0.01 # seconds (0.01s == 10ms)

# TODO: sets local state equal to data on event
def twist_callback(data):
	pass

# TODO: sets local state equal to data on event. 
def command_callback(data): 
	pass

# TODO: publishes smoothed velocity value and state value to kobuki. this is called every 10ms
def publish_callback(data):
	velocity_pub.publish()
	pass

# master rate is every 10ms (100hz)
# TODO: takes published values $(SMOOTHING_RATE) closer to input values, publishes every 10ms (0.01s)
if __name__ == '__main__':
	# calls publish_callback every 0.01s
	smoothing_timer = rospy.Timer(rospy.Duration(DURATION_S), publish_callback) 

''' OLD float_smoother
value = 0.0
target = 0.0

ECO_DELTA = 0.01
SPORT_DELTA = 0.005

def callback(data):
    global target
    target = data.data

def listener():
    global value, target

    rospy.init_node("smoother", anonymous=True)
	rospy.init_node("robot_commands", Int32MultiArray, config
    rospy.Subscriber("robot_twist", Twist, callback)

    rate = rospy.Rate(10)

    while not rospy.is_shutdown():
        print value

	if value > target:
		value = value - 0.01
		if value < target:
			value = target
	elif value < target:
		value = value + 0.01
		if value > target:
			value = target
	rate.sleep()

if __name__ == '__main__':
    listener()
'''
